build:
  environment:
    php:
      version: "8.3"
  nodes:
    analysis:
      before_commands:
        - composer self-update --2
        - composer install --no-interaction --no-scripts
      tests:
        override: [ php-scrutinizer-run ]

tools:
  php_code_coverage:
    enabled: true
    external_code_coverage:
      timeout: 600
  php_code_sniffer: true
  psalm: true

checks:
  php:
    code_rating: true
    duplication: true
